config/routes.rb
Rails.application.routes.draw do

  resources :user_table_sessions
  resources :warehouse_vendors do
    collection do
      post  :load_warehouse_vendor
      post :update_fields
      get :list
    end
  end
  resources :customer_invoices do
    member do
      get :print
    end
    collection do
      post :generate_invoice
    end
  end
  resources :invoices,  only: [:index, :show] do
    collection do
      post :list
      post  :updateitem
      post  :set_invoice
    end
  end
  resources :inbound_shipments do
    collection do
      get :create_from_plan
      get :getshipmentofstage
      get :additemfromstage
      get :removeitem
    end
    member do
      get :reset_transport_plan
      get :sync_transport_plan
      get :void_transport_plan
      get :mark_as_shipped
      get :send_invoice
      post :add_invoice
    end
  end
  resources :mws_orders
  resources :user_market_places
  resources :mws_report_requests
  # resources :outbound_shipments
  resources :seller_skus
  get '/sellerskus/load' => 'seller_skus#load'

  devise_scope :user do
    # root to: "skynets#new"
    get 'users/sign_out' => "devise/sessions#destroy"
  end

  resources :pull_inventories
  resources :skynets
  resources :vendors do
    member do
      get :supplier
    end
  end
  resources :vendor_categories
  resources :vendoritems do
    collection do
      get :getvendoritem
      post :check_sku
    end
  end
  resources :subscriptions
  resources :pos
  resources :pending_pos do
    collection do
      post :complete
      post  :receive
      # post :recreate_sku
      get :recreate_sku
      get :remove_sku
      get :check_sku
      get :list_options
      get  :list_all_po
      post  :updateitem
    end
  end
  resources :pending_po_indices do
    collection do
      get :loadsummary
      get :list
      post :updateitem
    end
  end
  resources :ship_cus_invoices do
    collection do
      get :load_invoices
      post :updateitem
    end
    member do
      get :send_invoice
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :users, only: [:edit, :update, :create, :new, :destroy] do
    collection do
      post :update_warehouse
    end
  end
  get '/profile' => 'users#profile'
  # authenticated :user do
    # root to: "skynets#new"
  # end

  get '/plans' => 'subscriptions#plans'
  get '/stripe_notification' => 'subscriptions#stripe_notification'
  post '/stripe_checkout' => 'subscriptions#stripe_checkout'
  post '/subscription_checkout' => 'subscriptions#subscription_checkout'
  get '/stripe_charge' => 'subscriptions#stripe_charge'
  get '/stripe_mini_charge' => 'subscriptions#stripe_mini_charge'
  post '/stripe_charge_check' => 'subscriptions#stripe_charge_check'

  get '/welcome' => 'subscriptions#welcome'

  resources :companies

  get '/' => 'home#index'
  # defaults to dashboard
  root :to => redirect('/')

  # view routes
  get '/userlist' => 'home#userlist'
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'
  get 'dashboard/dashboard_buyer'
  get 'dashboard/dashboard_manager'
  get 'dashboard/dashboard_admin'
  get 'dashboard/dashboard_h'

  get '/download' => 'skynets#download'
  get '/skynets/history' => 'skynets#history'

  post '/skynets/uploadfile' => 'skynets#uploadfile'
  post 'updateskynetstatus' => 'skynets#updateskynetstatus'
  post 'insertskynet' => 'skynets#insertskynet'
  post 'importxml' => 'skynets#import_xml'
  post 'testxml' => 'skynets#testxml'
  post 'updatemissingasin' => 'skynets#updatemissingasin'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end


  post 'updatevendoritem' =>'vendoritems#updatevendoritem'
  post 'deletevendoritem' =>'vendoritems#deletevendoritem'
  post 'addvendoritem' =>'vendoritems#addvendoritem'

  get 'getprofitable' =>'vendoritems#getprofitable'

  namespace :api do
    get 'skynethisotry' => 'skynet#skynethisotry'
    get 'deleteskynet' => 'skynet#deleteskynet'
    get 'getitemlist' => 'vendoritem#getitemlist'
    post 'refreshitems' => 'vendoritem#refreshitems'
    get 'send_to_po' => 'vendoritem#send_to_po'
  end

  post 'po'=> 'po#upload'
  post 'po/uploadfile' => 'po#uploadfile'
  post 'po/send' => 'po#sendpo'
  post 'po/send_pending' => 'po#send_pending'
  get 'po/index' => 'po#index'
  get 'po/list' => 'po#list'
  get 'po/listpo' => 'po#listpo'
  get 'po/load' => 'po#load'
  post 'po/delete' => 'po#delete'
  post 'po/deletebyvendor' => 'po#deletebyvendor'
  post 'po/updateitem' => 'po#updateitem'


  get 'pending_po/load' => 'pending_pos#load'
  get 'pending_po/loadpoindex' => 'pending_pos#loadpoindex'

  # get 'outbound_shipments/list_pending' => 'outbound_shipments/list_pending'
  resources :outbound_shipments do
    collection do
      get :list_pending
      get :list_pending_all
      get :getshipplanfromstage
      get :createshipplan
      get :bagger_list
      get :list_bagger
      get :getbagger
      get :printbagger
      get :get_previous_address

      post  :printsticker
      get :ajax_download
      post :check_shipplan
      post :send_bagger
      post :generate_shipment_hash
      get :get_box_information
      post :print_mix_2d_barcode
    end
    member do
      get :finalize_shipment
    end
  end

  resources :transport_plans do
    collection do
      post :initiate_estimate
      post :estimate
      post :initiate_confirmation
      post :confirm
      get :print_box_labels
      get :print_pallete_labels
      post :remove_package
      post :remove_pallete
      post :remove_tracking
      get :print_bill_of_lading
      get :print_2d_label
      post :submit_box_information
      get :print_mix_labels
    end
    member do
      get :get_estimates
      post :upload_to_amazon
      post :confirm_shipment
      post :add_packages
      get :box_information
      post :update_box_information
      post :update_shipping_fee
    end
  end

  get 'inbound_shipplans/loadshipplan' => 'inbound_shipplans#loadshipplan'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'home#create', as: 'create_message'

  get 'owner_steven' => 'admin#index'


  # get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  # get 'elements/dropdown'
  # get 'elements/nestable'
  # get 'elements/sortable'
  # get 'elements/panel'
  # get 'elements/portlet'
  get 'elements/grid'
  # get 'elements/gridmasonry'
  # get 'elements/typography'
  # get 'elements/fonticons'
  # get 'elements/weathericons'
  # get 'elements/colors'
  # get 'elements/buttons'
  # get 'elements/notifications'
  # get 'elements/carousel'
  # get 'elements/tour'
  # get 'elements/sweetalert'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  # get 'forms/wizard'
  # get 'forms/upload'
  # get 'forms/xeditable'
  # get 'forms/imgcrop'
  # get 'multilevel/level1'
  # get 'multilevel/level3'
  # get 'charts/flot'
  # get 'charts/radial'
  # get 'charts/chartjs'
  # get 'charts/chartist'
  # get 'charts/morris'
  # get 'charts/rickshaw'
  # get 'tables/standard'
  # get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  # get 'maps/google'
  # get 'maps/vector'
  # get 'extras/mailbox'
  # get 'extras/timeline'
  # get 'extras/calendar'
  # get 'extras/invoice'
  # get 'extras/search'
  # get 'extras/todo'
  # get 'extras/profile'
  # get 'extras/contacts'
  # get 'extras/contact_details'
  # get 'extras/projects'
  # get 'extras/project_details'
  # get 'extras/team_viewer'
  # get 'extras/social_board'
  # get 'extras/vote_links'
  # get 'extras/bug_tracker'
  # get 'extras/faq'
  # get 'extras/help_center'
  # get 'extras/followers'
  # get 'extras/settings'
  # get 'extras/plans'
  # get 'extras/file_manager'
  # get 'blog/blog'
  # get 'blog/blog_post'
  # get 'blog/blog_articles'
  # get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  # get 'ecommerce/ecommerce_order_view'
  # get 'ecommerce/ecommerce_products'
  # get 'ecommerce/ecommerce_product_view'
  # get 'ecommerce/ecommerce_checkout'
  # get 'forum/forum_categories'
  # get 'forum/forum_topics'
  # get 'forum/forum_discussion'
  # get 'pages/login'
  # get 'pages/register'
  # get 'pages/recover'
  # get 'pages/lock'
  # get 'pages/template'
  # get 'pages/notfound'
  # get 'pages/maintenance'
  # get 'pages/error500'

  # # api routes
  # get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  # get '/api/skynethisotry' => 'api#skynethisotry'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'

  get '/api/i18n/:locale' => 'api#i18n'

  get '/api/postbanner' => 'api#postbanner'
  get '/users/sendnotification'
  # post '/api/xeditable' => 'api#xeditable'
  # get '/api/xeditable-groups' => 'api#xeditablegroups'

  # # the rest goes to root
  # get '*path' => redirect('/')

end

app/controllers/pending_po_indices_controller.rb
class PendingPoIndicesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_manager, only: [:updateitem]
  before_action :set_pending_po_index, only: [:show, :edit, :update, :destroy]

  # GET /pending_po_indices
  # GET /pending_po_indices.json
  def index
    @pending_po_index_status = PendingPoIndex.status_list
    if current_user.is_warehouse
      @user_option = User.where(id: PendingPoIndex.joins(vendor: :user).pluck("users.id"))
      @po_option = PendingPoIndex.all
      @vendor_option = Vendor.where(id: PendingPoIndex.all.pluck("vendor_id"))
    else
      @user_option = [current_user]
      @po_option = current_user.pending_po_indices
		  @vendor_option = current_user.vendors.where(id: PendingPoIndex.all.pluck("vendor_id"))
    end  
    
  end

  # GET /pending_po_indices/1
  # GET /pending_po_indices/1.json
  def show
    @status_list = PendingPo.status_list
  end

  # GET /pending_po_indices/new
  def new
    @pending_po_index = PendingPoIndex.new
  end

  # GET /pending_po_indices/1/edit
  def edit
  end

  # POST /pending_po_indices
  # POST /pending_po_indices.json
  def create
    @pending_po_index = PendingPoIndex.new(pending_po_index_params)

    respond_to do |format|
      if @pending_po_index.save
        format.html { redirect_to @pending_po_index, notice: 'Pending po index was successfully created.' }
        format.json { render :show, status: :created, location: @pending_po_index }
      else
        format.html { render :new }
        format.json { render json: @pending_po_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pending_po_indices/1
  # PATCH/PUT /pending_po_indices/1.json
  def update
    respond_to do |format|
      if @pending_po_index.update(pending_po_index_params)
        format.html { redirect_to @pending_po_index, notice: 'Pending po index was successfully updated.' }
        format.json { render :show, status: :ok, location: @pending_po_index }
      else
        format.html { render :edit }
        format.json { render json: @pending_po_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pending_po_indices/1
  # DELETE /pending_po_indices/1.json
  def destroy
    @pending_po_index.destroy
    respond_to do |format|
      format.html { redirect_to pending_po_indices_url, notice: 'Pending po index was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def loadsummary
    start = params[:iDisplayStart].to_i
    limit = params[:iDisplayLength].to_i
    filter_status = params[:filter_status]

    if current_user.is_warehouse
      pending_po_indices = PendingPoIndex.all
    else
      pending_po_indices = current_user.pending_po_indices.all
    end
    
    pending_po_indices = pending_po_indices.joins(:vendor)
    # pending_filter = false
    pending_po_indices = pending_po_indices.per_status(filter_status)
    total = pending_po_indices.load.size
    iColumns = params[:iColumns].to_i
    (0...iColumns).step(1).each do |i|
      ori_search_column = params["mDataProp_#{i}"]
      search_column = ori_search_column.split(".")[-1]
      search = params["sSearch_#{i}"]
      unless search.nil? || search == ''
        if search_column == "po_name"
          pending_po_indices = pending_po_indices.where(:po_name => search)
        elsif ori_search_column == "vendor.warehouse_vendor.name"
          pending_po_indices = pending_po_indices.joins(vendor: :warehouse_vendor).where("warehouse_vendors.name = ?", search)
        elsif search_column == "full_name"
          pending_po_indices = pending_po_indices.joins(vendor: :user).where("concat_ws(' ',users.first_name, users.last_name) = ?", search)
        elsif search_column == "pending_status"
          # pending_filter = true
          # pending_po_indices = pending_po_indices.where("pending_po_indices.pending_status = ?", PendingPoIndex.pending_statuses[search.to_sym])
        elsif search_column == "name" || search_column == "supplier_prefix"
          pending_po_indices = pending_po_indices.joins(:vendor).where("vendors.#{search_column} = ?", search)
        end
      end
    end
    # unless pending_filter
    #   pending_po_indices = pending_po_indices.per_status(filter_status)
    # end
    
    filtered = pending_po_indices.load.size
    pending_po_indices = pending_po_indices.limit(limit).offset(start).joins({pending_pos: :vendoritem}, {vendor: :user}).includes({pending_pos: :vendoritem}, {vendor: [:warehouse_vendor, :user]})
    render json: {
      # 'aaData'=>pending_po_indices.includes(:pending_pos, vendor: :warehouse_vendor),
      'aaData'=>pending_po_indices.as_json(
        methods: [:order_qty, :order_e_cost, :confirmed_qty, :confiremd_e_cost, :received_quantity, :total_shipped_pack, :sku_count, :missing_quantity],
        include: [{pending_pos: {include: :vendoritem}}, {vendor: {include: [:warehouse_vendor, user: {methods: :full_name}]}}]
      ),
      "iTotalRecords": total,
      "iTotalDisplayRecords": filtered}
  end

  def list
    render json: {'aaData'=>current_user.pending_po_indices} 
  end

  def list_options
    render json: {'status_list'=>PendingPoIndex.status_list}
  end

  def updateitem
    pending_po_index = nil
    data = params[:data]
    data.each do |key, item|
      pending_po_index = PendingPoIndex.find(key)
      item.each do |title, value|
        pending_po_index[title.to_sym] = value
      end
      pending_po_index.save
    end
    render json: {'data'=>pending_po_index}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pending_po_index
      begin
        @pending_po_index = PendingPoIndex.find(params[:id])
        unless @pending_po_index.vendor.user == current_user || current_user.is_warehouse
          redirect_to po_list_path
        end
      rescue ActiveRecord::RecordNotFound => e
        redirect_to po_list_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pending_po_index_params
      params.fetch(:pending_po_index, {})
    end
end

app/helpers/pending_po_indices_helper.rb
module PendingPoIndicesHelper
end

app/views/pending_po_indices/_form.html.erb
<%= form_for(pending_po_index) do |f| %>
  <% if pending_po_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pending_po_index.errors.count, "error") %> prohibited this pending_po_index from being saved:</h2>

      <ul>
      <% pending_po_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pending_po_indices/edit.html.erb
<h1>Editing Pending Po Index</h1>

<%= render 'form', pending_po_index: @pending_po_index %>

<%= link_to 'Show', @pending_po_index %> |
<%= link_to 'Back', pending_po_indices_path %>

app/views/pending_po_indices/index.html.erb
<style type="text/css">
  .btn-primary.active {
    background-color: #5555e7 !important;
  }
</style>
<p id="notice"><%= notice %></p>

<div id="content">
  <div class="content-inner">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-primary  btn-lg filter-status">
                        <input id="option8" name="options" type="radio" value="All">
                        ALL <%= @po_option.per_status("All").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg filter-status active">
                        <input id="option0" name="options" type="radio" value="">
                        No Status <%= @po_option.per_status("").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option1" name="options" type="radio" value="Sent">
                        Sent <%= @po_option.per_status("Sent").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option2" name="options" type="radio" value="Confirmed">
                        Confirmed <%= @po_option.per_status("Confirmed").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option3" name="options" type="radio" value="Payment">
                        Payment <%= @po_option.per_status("Payment").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option4" name="options" type="radio" value="Inbound">
                        Inbound <%= @po_option.per_status("Inbound").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option5" name="options" type="radio" value="Invoice">
                        Invoice <%= @po_option.per_status("Invoice").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option6" name="options" type="radio" value="Rep Payout">
                        Rep Payout <%= @po_option.per_status("Rep Payout").count %>
                    </label>
                    <label class="btn btn-primary  btn-lg  filter-status">
                        <input id="option7" name="options" type="radio" value="Completed">
                        Completed <%= @po_option.per_status("Completed").count %>
                    </label>
                </div>
            </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
            <div class="table-responsive">
                <table id="datatable_pending_po_summary" class="display " style="width: 100%">
                  <thead>
                     <tr>
                      <th>PO</th>
                      <th>Created</th>
                      <th>Customer</th>
                      <th >Vendor</th>
                      <th >SUPPLIER</th>
                      <th>Status</th>
                      <th >ORDERS Qty</th>
                      <th >CONFIRMED Qty</th>
                      <th>Received Qty</th>
                      <th>Total Shipped Qty</th>
                      <th>Missing Qty</th>
                      <th>ORDERS E.Cost</th>
                      <th >CONFIRMED E.Cost</th>
                     </tr>
                     <tr id="filterrow" class="datatable_filter_header">
                      <th>PO</th>
                      <th>Created</th>
                      <th>Customer</th>
                      <th >Vendor</th>
                      <th >SUPPLIER</th>
                      <th>Status</th>
                      <th >ORDERS Qty</th>
                      <th >CONFIRMED Qty</th>
                      <th>Received Qty</th>
                      <th>Total Shipped Qty</th>
                      <th>Missing Qty</th>
                      <th>ORDERS E.Cost</th>
                      <th >CONFIRMED E.Cost</th>
                    </tr>
                  </thead>
                  <tbody></tbody>
                  <tfoot>
                    
                  </tfoot>
               </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- end content inner -->
</div><!-- end content -->
<%= render partial: "layouts/partials/useroption" %>
<%= javascript_tag do %>
  
<% end %>
<% content_for :page_scripts do %>
  <% @pending_po_index_status.each do |s| %>
    <script>
    select_option_status_list.push({
      value: "<%= s["value"] %>",
      label: "<%= s["value"] %>",
    });
    </script>
  <% end %>
  <% if current_user.is_warehouse %>
    <script>
      status_class = "number_cell editable";
    </script>
  <% end %>
  <script>
    $(document).ready(function(){
      initPendigPoEditor();
      loadpendingpo_summary_table();
    });
  </script>
<% end %>

app/views/pending_po_indices/new.html.erb
<h1>New Pending Po Index</h1>

<%= render 'form', pending_po_index: @pending_po_index %>

<%= link_to 'Back', pending_po_indices_path %>

app/views/pending_po_indices/show.html.erb
<style type="text/css">
.modal-dialog {
    margin: 80px auto;
  }
tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }
    div.dataTables_wrapper {
        margin: 0 auto;
    }
    th input {
        width: 90%;
        min-width: 50px;
    }

    tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }

    .modal-backdrop
    {
      display: none;
    }

    tfoot {
      display: table-header-group;
    }
</style>
<% unless !@name || @name.blank? %>
  <style type="text/css">
    .boldspan{ 
      font-weight: bolder;
      font-size: 18px;
    }
  </style>
<% end %>
<div id="content">
  <div class="content-inner">
    <div class="panel panel-default">
      <div class="panel-heading col-lg-12">
        <div class="panel-title col-lg-5">
          <b><%= @pending_po_index.po_name %></b>
        </div>
      </div>
      <div class="panel-body">
        <div class="row pv-lg">
          <div class="col-lg-12">
            <div class="table-responsive">
                <table id="datable_pending_po" class="display " style="width: 100%">
                  <thead>
                     <tr>
                      <th></th>
                      <th >ID</th>
                      <th style="min-width:200px; max-width: 350px;">NAME</th>
                      <th >SKU</th>
                      <th >ASIN</th>
                      <th>VendorSKU</th>
                      <th >UPC</th>
                      <th>Order Quantity</th>
                      <th>Received Quantity</th>
                      <th>Confirmed Quantity</th>
                      <th>Order Cost</th>
                      <th>Confirmed Cost</th>
                      <th>COST</th>
                      <th>Packcount</th>
                      <th>PackCost</th>
                      <th>Status</th>
                      <th>Date</th>
                      <th >BBP</th>
                      <th >SalesRank</th>
                      <th>Profit</th>
                      <th>Margin</th>
                      <th>FBAfee</th>
                      <th>ComPCT</th>
                      <th>ComFee</th>
                      <th>EST</th>
                      <th>OFFER</th>
                      <th>FBA</th>
                      <th>FBM</th>
                      <th>ItemId</th>
                     </tr>
                     <tr id="filterrow">
                      <th></th>
                      <th >ID</th>
                      <th style="min-width:200px; max-width: 350px;">NAME</th>
                      <th >SKU</th>
                      <th >ASIN</th>
                      <th>VendorSKU</th>
                      <th >UPC</th>
                      <th>Order Quantity</th>
                      <th>Received Quantity</th>
                      <th>Confirmed Quantity</th>
                      <th>Order Cost</th>
                      <th>Confirmed Cost</th>
                      <th>COST</th>
                      <th>Packcount</th>
                      <th>PackCost</th>
                      <th>Status</th>
                      <th>Date</th>
                      <th >BBP</th>
                      <th >SalesRank</th>
                      <th>Profit</th>
                      <th>Margin</th>
                      <th>FBAfee</th>
                      <th>ComPCT</th>
                      <th>ComFee</th>
                      <th>EST</th>
                      <th>OFFER</th>
                      <th>FBA</th>
                      <th>FBM</th>
                      <th>ItemId</th>
                    </tr>
                  </thead>
                  <tbody></tbody>
                  <tfoot>
                    
                  </tfoot>
               </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- end content inner -->
</div><!-- end content -->
<%= render partial: "layouts/partials/multifilter" %>
<%= javascript_tag do %>
  window.pending_po_id = "<%= @pending_po_index.id %>";
<% end %>

<% content_for :page_scripts do %>
  <% @status_list.each do |s| %>
    <script>
    select_option_status_list.push({
      value: "<%= s["value"] %>",
      label: "<%= s["value"] %>",
    });
    </script>
  <% end %>
  <% if current_user.is_warehouse %>
    <script>
      status_class = "number_cell editable";
    </script>
  <% end %>
  <script>
    $(document).ready(function(){
      loadpendingpotable(pending_po_id);
      initPendigPoItemEditor();
      initComplete();
    });
  </script>
<% end %>