config/routes.rb
Rails.application.routes.draw do

  resources :user_table_sessions
  resources :warehouse_vendors do
    collection do
      post  :load_warehouse_vendor
      post :update_fields
      get :list
    end
  end
  resources :customer_invoices do
    member do
      get :print
    end
    collection do
      post :generate_invoice
    end
  end
  resources :invoices,  only: [:index, :show] do
    collection do
      post :list
      post  :updateitem
      post  :set_invoice
    end
  end
  resources :inbound_shipments do
    collection do
      get :create_from_plan
      get :getshipmentofstage
      get :additemfromstage
      get :removeitem
    end
    member do
      get :reset_transport_plan
      get :sync_transport_plan
      get :void_transport_plan
      get :mark_as_shipped
      get :send_invoice
      post :add_invoice
    end
  end
  resources :mws_orders
  resources :user_market_places
  resources :mws_report_requests
  # resources :outbound_shipments
  resources :seller_skus
  get '/sellerskus/load' => 'seller_skus#load'

  devise_scope :user do
    # root to: "skynets#new"
    get 'users/sign_out' => "devise/sessions#destroy"
  end

  resources :pull_inventories
  resources :skynets
  resources :vendors do
    member do
      get :supplier
    end
  end
  resources :vendor_categories
  resources :vendoritems do
    collection do
      get :getvendoritem
      post :check_sku
    end
  end
  resources :subscriptions
  resources :pos
  resources :pending_pos do
    collection do
      post :complete
      post  :receive
      # post :recreate_sku
      get :recreate_sku
      get :remove_sku
      get :check_sku
      get :list_options
      get  :list_all_po
      post  :updateitem
    end
  end
  resources :pending_po_indices do
    collection do
      get :loadsummary
      get :list
      post :updateitem
    end
  end
  resources :ship_cus_invoices do
    collection do
      get :load_invoices
      post :updateitem
    end
    member do
      get :send_invoice
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :users, only: [:edit, :update, :create, :new, :destroy] do
    collection do
      post :update_warehouse
    end
  end
  get '/profile' => 'users#profile'
  # authenticated :user do
    # root to: "skynets#new"
  # end

  get '/plans' => 'subscriptions#plans'
  get '/stripe_notification' => 'subscriptions#stripe_notification'
  post '/stripe_checkout' => 'subscriptions#stripe_checkout'
  post '/subscription_checkout' => 'subscriptions#subscription_checkout'
  get '/stripe_charge' => 'subscriptions#stripe_charge'
  get '/stripe_mini_charge' => 'subscriptions#stripe_mini_charge'
  post '/stripe_charge_check' => 'subscriptions#stripe_charge_check'

  get '/welcome' => 'subscriptions#welcome'

  resources :companies

  get '/' => 'home#index'
  # defaults to dashboard
  root :to => redirect('/')

  # view routes
  get '/userlist' => 'home#userlist'
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'
  get 'dashboard/dashboard_buyer'
  get 'dashboard/dashboard_manager'
  get 'dashboard/dashboard_admin'
  get 'dashboard/dashboard_h'

  get '/download' => 'skynets#download'
  get '/skynets/history' => 'skynets#history'

  post '/skynets/uploadfile' => 'skynets#uploadfile'
  post 'updateskynetstatus' => 'skynets#updateskynetstatus'
  post 'insertskynet' => 'skynets#insertskynet'
  post 'importxml' => 'skynets#import_xml'
  post 'testxml' => 'skynets#testxml'
  post 'updatemissingasin' => 'skynets#updatemissingasin'

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end


  post 'updatevendoritem' =>'vendoritems#updatevendoritem'
  post 'deletevendoritem' =>'vendoritems#deletevendoritem'
  post 'addvendoritem' =>'vendoritems#addvendoritem'

  get 'getprofitable' =>'vendoritems#getprofitable'

  namespace :api do
    get 'skynethisotry' => 'skynet#skynethisotry'
    get 'deleteskynet' => 'skynet#deleteskynet'
    get 'getitemlist' => 'vendoritem#getitemlist'
    post 'refreshitems' => 'vendoritem#refreshitems'
    get 'send_to_po' => 'vendoritem#send_to_po'
  end

  post 'po'=> 'po#upload'
  post 'po/uploadfile' => 'po#uploadfile'
  post 'po/send' => 'po#sendpo'
  post 'po/send_pending' => 'po#send_pending'
  get 'po/index' => 'po#index'
  get 'po/list' => 'po#list'
  get 'po/listpo' => 'po#listpo'
  get 'po/load' => 'po#load'
  post 'po/delete' => 'po#delete'
  post 'po/deletebyvendor' => 'po#deletebyvendor'
  post 'po/updateitem' => 'po#updateitem'


  get 'pending_po/load' => 'pending_pos#load'
  get 'pending_po/loadpoindex' => 'pending_pos#loadpoindex'

  # get 'outbound_shipments/list_pending' => 'outbound_shipments/list_pending'
  resources :outbound_shipments do
    collection do
      get :list_pending
      get :list_pending_all
      get :getshipplanfromstage
      get :createshipplan
      get :bagger_list
      get :list_bagger
      get :getbagger
      get :printbagger
      get :get_previous_address

      post  :printsticker
      get :ajax_download
      post :check_shipplan
      post :send_bagger
      post :generate_shipment_hash
      get :get_box_information
      post :print_mix_2d_barcode
    end
    member do
      get :finalize_shipment
    end
  end

  resources :transport_plans do
    collection do
      post :initiate_estimate
      post :estimate
      post :initiate_confirmation
      post :confirm
      get :print_box_labels
      get :print_pallete_labels
      post :remove_package
      post :remove_pallete
      post :remove_tracking
      get :print_bill_of_lading
      get :print_2d_label
      post :submit_box_information
      get :print_mix_labels
    end
    member do
      get :get_estimates
      post :upload_to_amazon
      post :confirm_shipment
      post :add_packages
      get :box_information
      post :update_box_information
      post :update_shipping_fee
    end
  end

  get 'inbound_shipplans/loadshipplan' => 'inbound_shipplans#loadshipplan'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'home#create', as: 'create_message'

  get 'owner_steven' => 'admin#index'


  # get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  # get 'elements/dropdown'
  # get 'elements/nestable'
  # get 'elements/sortable'
  # get 'elements/panel'
  # get 'elements/portlet'
  get 'elements/grid'
  # get 'elements/gridmasonry'
  # get 'elements/typography'
  # get 'elements/fonticons'
  # get 'elements/weathericons'
  # get 'elements/colors'
  # get 'elements/buttons'
  # get 'elements/notifications'
  # get 'elements/carousel'
  # get 'elements/tour'
  # get 'elements/sweetalert'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  # get 'forms/wizard'
  # get 'forms/upload'
  # get 'forms/xeditable'
  # get 'forms/imgcrop'
  # get 'multilevel/level1'
  # get 'multilevel/level3'
  # get 'charts/flot'
  # get 'charts/radial'
  # get 'charts/chartjs'
  # get 'charts/chartist'
  # get 'charts/morris'
  # get 'charts/rickshaw'
  # get 'tables/standard'
  # get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  # get 'maps/google'
  # get 'maps/vector'
  # get 'extras/mailbox'
  # get 'extras/timeline'
  # get 'extras/calendar'
  # get 'extras/invoice'
  # get 'extras/search'
  # get 'extras/todo'
  # get 'extras/profile'
  # get 'extras/contacts'
  # get 'extras/contact_details'
  # get 'extras/projects'
  # get 'extras/project_details'
  # get 'extras/team_viewer'
  # get 'extras/social_board'
  # get 'extras/vote_links'
  # get 'extras/bug_tracker'
  # get 'extras/faq'
  # get 'extras/help_center'
  # get 'extras/followers'
  # get 'extras/settings'
  # get 'extras/plans'
  # get 'extras/file_manager'
  # get 'blog/blog'
  # get 'blog/blog_post'
  # get 'blog/blog_articles'
  # get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  # get 'ecommerce/ecommerce_order_view'
  # get 'ecommerce/ecommerce_products'
  # get 'ecommerce/ecommerce_product_view'
  # get 'ecommerce/ecommerce_checkout'
  # get 'forum/forum_categories'
  # get 'forum/forum_topics'
  # get 'forum/forum_discussion'
  # get 'pages/login'
  # get 'pages/register'
  # get 'pages/recover'
  # get 'pages/lock'
  # get 'pages/template'
  # get 'pages/notfound'
  # get 'pages/maintenance'
  # get 'pages/error500'

  # # api routes
  # get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  # get '/api/skynethisotry' => 'api#skynethisotry'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'

  get '/api/i18n/:locale' => 'api#i18n'

  get '/api/postbanner' => 'api#postbanner'
  get '/users/sendnotification'
  # post '/api/xeditable' => 'api#xeditable'
  # get '/api/xeditable-groups' => 'api#xeditablegroups'

  # # the rest goes to root
  # get '*path' => redirect('/')

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id             :integer          not null, primary key
#  subscriptionid :string(255)
#  amount         :integer
#  interval       :string(255)
#  created        :integer
#
# Indexes
#
#  index_subscriptions_on_subscriptionid  (subscriptionid) UNIQUE
#

class Subscription < ApplicationRecord
  has_many :users
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  layout 'subscription'
  require "stripe"

  def index
  end

  def create
  	subscription = Stripe::Plan.create(
  	  # :amount => (params[:amount].to_i)*100,
  	  # :interval => params[:interval],
  	  # :name => params[:name],
  	  # :currency => 'usd',
  	  # :id => SecureRandom.uuid # This ensures that the plan is unique
      :amount => 0,
      :interval => 0,
      :name => '',
      :currency => 'usd',
      :id => SecureRandom.uuid
  	)
  	#Save the response to your DB
  	flash[:notice] = "Plan successfully created"
    	redirect_to '/subscription'
  end

  def plans
    begin
      @stripe_list = Stripe::Plan.all
      @plans = @stripe_list[:data]
      @plans = @plans.reverse  
    rescue Exception => e
      
    end
  	
  end

  def welcome
    # @stripe_list = Stripe::Plan.all
    # @plans = @stripe_list[:data]
    # @plans = @plans.reverse
  end

  def stripe_notification
    
  end

  def stripe_checkout
    # current_user.subscription_id = "stripe_subscription.id"
    # current_user.save
    # redirect_to '/skynets/new'
		@amount = params[:amount]
    @code = params[:couponCode]
    @final_amount = @amount
    if !@code.blank?
      @discount = get_discount(@code)
      if @discount.nil?
        redirect_to '/plans', :flash => { :coupon_error => "Coupon code is not valid or expired." } 
        return
        @discount = 0
        @code=""
      else
        @discount_amount = @amount * @discount
        @final_amount = @amount.to_i - @discount_amount.to_i
      end

      charge_metadata = {
        :coupon_code => @code,
        :coupon_discount => (@discount * 100).to_s + "%"
      }
    end

    begin
      @plan_id = params[:plan_id]
      @plan = Stripe::Plan.retrieve(@plan_id)
      
      puts "************* PLAN ****************"
      puts @plan

      customer = Stripe::Customer.create(
        :description => "Customer for" + current_user.email,
        :source => params[:stripeToken],
        :email => current_user.email
      )
      
      puts "************* customer ****************"
      puts customer
      
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount => @amount,
        :currency => "usd",
        :description => "Charge",
        :metadata    => charge_metadata
      )
      flash[:notice] = "Successfully created a charge"
      if params[:charge].nil?
        stripe_subscription = customer.subscriptions.create(:plan => @plan.id)
        @interval =  stripe_subscription.items.data[0].plan.interval
        @amount =  stripe_subscription.items.data[0].plan.amount
        @created =  stripe_subscription.items.data[0].plan.created
        subscription = Subscription.where(:subscriptionid => stripe_subscription.id,:interval=>@interval, :amount=>@amount,:created=>@created).first_or_create
        current_user.subscription_id = stripe_subscription.id
        current_user.active = 1  
      end
      
      if current_user.save
        redirect_to '/skynets/new'
      else
        redirect_to '/skynets/new', :flash => { :error => "Failed to charge."}
      end
    rescue Exception => e

      puts "************* Exception ****************"
      puts e.message
      if params[:charge]
        redirect_to '/stripe_charge', :flash => { :coupon_error => "Failed to charge."}
      else
        redirect_to '/plans', :flash => { :coupon_error => "Failed to charge." }   
      end
      
    end
  
  end
  def subscription_checkout

    @plan_id = params[:plan_id]
    @plan = Stripe::Plan.retrieve(@plan_id)
    #This should be created on signup.
    customer = Stripe::Customer.create(
      :description => "Customer for test@example.com",
      :source => params[:stripeToken],
      :email => "test@example.com"
    )
    # Save this in your DB and associate with the user;s email
    stripe_subscription = customer.subscriptions.create(:plan => @plan.id)
    @interval =  stripe_subscription.items.data[0].plan.interval
    @amount =  stripe_subscription.items.data[0].plan.amount
    @created =  stripe_subscription.items.data[0].plan.created
    subscription = Subscription.where(:subscriptionid => stripe_subscription.id,:interval=>@interval, :amount=>@amount,:created=>@created).first_or_create
    current_user.subscription_id = stripe_subscription.id
    # flash[:notice] = "Successfully created a charge"
    # redirect_to '/plans'
    if current_user.save
        redirect_to '/skynets/new'
    else
      return
    end    
  end

  def stripe_charge_check
    if params[:stripeToken]
      begin
        customer = Stripe::Customer.create(
          :description => "Customer for" + current_user.email,
          :source => params[:stripeToken],
          :email => params[:stripeEmail]
        )
       
        
        charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount => params[:amount],
          :currency => "usd",
          :description => "Charge",
        )
        current_user.active = 1
        if current_user.save
          redirect_to '/skynets/new'
          return
        end  
      rescue Exception => e
          redirect_to '/stripe_charge', :flash => { :coupon_error => "e.message" }    
          return
      end
      
    end
    redirect_to '/stripe_charge', :flash => { :coupon_error => "Failed to charge." }
  end

  def stripe_charge
    
  end

  def stripe_mini_charge
    
  end

  private 
  COUPONS = {
    '1233020020073056' => 1,
    '816554411748126' => 1
  }
  
  def get_discount(code)
  # Normalize user input
    code = code.gsub(/\s+/, '')
    code = code.upcase
    COUPONS[code]
  end

end

app/views/subscriptions/plans.html.erb
<div class="subscription_plan">
    <div id="pricing-table" class="clear">     
        <div class="col-md-3 col-sm-6">
            <%= form_tag('/stripe_checkout',{method: :post, autocomplete: :"off"})  do  %>
                <div class="plan">
                    <%= hidden_field_tag "plan_id", "cfe53be3-d40d-4d25-8e6c-f380c2f725a6" %>
                    <%= hidden_field_tag "amount", 900 %>
                    <%= hidden_field_tag "couponCode","",:class=>"couponcode" %>
                    <!-- <input class="couponcode" name="couponCode" type="hidden" value= 0 > -->
                    <p>
                    </p>
                    <h3><%= 'Lite' %><span>$<%= 9.99 %></span></h3>
                    <ul>
                        <li><b><%= 30 %></b> Day Free Trial</li>
                        <li>Daily Vendor Suggestions</li>
                        <li>Analysis up to 100k Sku Catalogs Daily</li>
                    </ul>
                    <div class= "buttons">
                        <button type="submit" class="pay-btn"><span>Choose Plan</span></button>
                        <!-- <script src="https://checkout.stripe.com/checkout.js" class="stripe-button paybtn"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="A month's subscription"
                            data-amount=<%= 900 %>
                            data-locale="auto">
                        </script> -->
                    </div>
                </div>
            <% end %>
        </div>  
        <div class="col-md-3 col-sm-6">
            <%= form_tag('/stripe_checkout',{method: :post, autocomplete: :"off"})  do  %>
                <div class="plan">
                    <%= hidden_field_tag "plan_id", "29.99" %>
                    <%= hidden_field_tag "amount", 2900 %>
                    <%= hidden_field_tag "couponCode","",:class=>"couponcode" %>
                    <p>
                    </p>
                    <h3><%= 'Mid' %><span>$<%= 29.99 %></span></h3>
                    <ul>
                        <li><b><%= 30 %></b> Day Free Trial</li>
                        <li>Includes "Buy Now" Filter</li>
                        <li>Daily refresh BBP and Sales Rank</li>
             
                    </ul>
                    <div class= "buttons">
                        <button type="submit" class="pay-btn"><span>Choose Plan</span></button>
                        <!-- <script src="https://checkout.stripe.com/checkout.js" class="stripe-button paybtn"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="A month's subscription"
                        data-amount=<%= 900 %>
                        data-locale="auto">
                        </script> -->
                    </div>
                </div>
            <% end %>
        </div>
        
         
        <div class="col-md-3 col-sm-6">
            <%= form_tag('/stripe_checkout',{method: :post, autocomplete: :"off"})  do  %>
            <div class="plan">
                <%= hidden_field_tag "plan_id", "Enterprise" %>
                <%= hidden_field_tag "amount", 4900 %>
                <%= hidden_field_tag "couponCode","",:class=>"couponcode" %>
                <p></p>
                <h3><%= 'Executive' %><span>$<%= 49.99 %></span></h3>
                <ul>
                    <li><b><%= 30 %></b>  Day Free Trial</li>
                    <li>Purchase Orders and oh so much more</li>
                </ul>
                <div class= "buttons">
                    <button type="submit" class="pay-btn"><span>Choose Plan</span></button>
                    <!-- <script src="https://checkout.stripe.com/checkout.js" class="stripe-button paybtn"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="A month's subscription"
                      data-amount=<%= 900 %>
                      data-locale="auto">
                    </script> -->
                </div>
            </div>
            <% end %>
        </div>
        <div class="col-md-3 col-sm-6">
            <%= form_tag('/stripe_checkout',{method: :post, autocomplete: :"off"})  do  %>

            <div class="plan">
                <%= hidden_field_tag "plan_id", "enterprise" %>  
                <h3><%= "Enterprise" %></h3>
                <div class="contactform">
                    <h4>Contact for pricing</h4>
                </div>
                <br>
                <ul>
                    <li>Custom quotes</li>
                    <li>Outbound shipments</li>
                    <li>Inbound Claims</li>
                </ul>
            </div>
            <div class= "buttons">
                <button type="submit" class="pay-btn"><span>Choose Plan</span></button>
                <!-- <script src="https://checkout.stripe.com/checkout.js" class="stripe-button paybtn"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="A month's subscription"
                    data-amount=<%= 900 %>
                    data-locale="auto">
                </script> -->
            </div>
            <% end %>
      </div>
       
      <div class="promo">
        <span>Promo Code:</span>
        <!--<%= text_field_tag  (:couponCode )  %> -->
        <input type="text" onchange="changedCouponCode(this.value)">
         <% flash.each do |key, value| %>
           <% if key=="coupon_error" %>
              <div style="font-size:30px;color:red">
                    <%= value %>
              </div>
            <% end %>
        <% end %>
      </div>
  </div>
</div>

 <script>
    
    var buttons = document.getElementsByClassName("stripe-button-el");
    for (var i=0; i < buttons.length; i++){
      document.getElementsByClassName("stripe-button-el")[i].children[0].innerText = 'Start Free Trail';  
      document.getElementsByClassName("stripe-button-el")[i].addEventListener("click", onClickTrialButton);
    }
    function changedCouponCode(val){
      console.log(val);
      var couponcodes = document.getElementsByClassName("couponcode");
      for (var i=0; i < couponcodes.length; i++){
        document.getElementsByClassName("couponcode")[i].value = val; 
      }
    }
    function onClickTrialButton(){

      // var iframe = document.getElementsByTagName("iframe");
      // console.log(iframe);
      // var iframeDoc = (iframe[0].contentDocument) ? iframe[0].contentDocument : iframe[0].contentWindow.document;
      // iframeDoc.getElementsByClassName("Button-content")[0].children[0].innerText="Start Free Trial";
      // iframeDoc.getElementsByClassName("Button-content")[0].children[0].children[0].children[0].innerText="";
    }
  </script>

app/views/subscriptions/stripe_charge.html.erb
<div class="subscription_plan">
    <div id="pricing-table" class="clear">     
        <div class="col-md-3 col-sm-6">
            <% flash.each do |key, value| %>
               <% if key=="coupon_error" %>
                  <div style="font-size:30px;color:red">
                        <%= value %>
                  </div>
                <% end %>
            <% end %>
            <%= form_tag('/stripe_charge_check',{method: :post, autocomplete: :"off"})  do  %>
                <div class="plan">
                    <%= hidden_field_tag "plan_id", "plan_DsPMx27018zMGT" %>
                    <%= hidden_field_tag "amount", 19900 %>
                    <%= hidden_field_tag "charge", 1 %>
                    <p>
                    </p>
                    <h3><%= 'Enterprise' %><span>$<%= 199 %></span></h3>
                    <ul>
                        <li>Daily Vendor Suggestions</li>
                        <li>Analysis up to 100k Sku Catalogs Daily</li>
                    </ul>
                    <div class= "buttons">
                        <!-- <button type="submit" class="pay-btn"><span>Choose Plan</span></button> -->
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button paybtn"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="A month's subscription"
                            data-amount=<%= 19900 %>
                            data-locale="auto">
                        </script>
                    </div>
                </div>
            <% end %>
        </div>  
  </div>

</div>

 <script>
    
    /*var buttons = document.getElementsByClassName("stripe-button-el");
    for (var i=0; i < buttons.length; i++){
      document.getElementsByClassName("stripe-button-el")[i].children[0].innerText = 'Start Free Trail';  
      document.getElementsByClassName("stripe-button-el")[i].addEventListener("click", onClickTrialButton);
    }
    
    function onClickTrialButton(){

      var iframe = document.getElementsByTagName("iframe");
      console.log(iframe);
      var iframeDoc = (iframe[0].contentDocument) ? iframe[0].contentDocument : iframe[0].contentWindow.document;
      iframeDoc.getElementsByClassName("Button-content")[0].children[0].innerText="Start Free Trial";
      iframeDoc.getElementsByClassName("Button-content")[0].children[0].children[0].children[0].innerText="";
    }*/
  </script>

app/views/subscriptions/stripe_mini_charge.html.erb
<div class="subscription_plan">
    <div id="pricing-table" class="clear">     
        <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3" >
            <% flash.each do |key, value| %>
               <% if key=="coupon_error" %>
                  <div style="font-size:30px;color:red">
                        <%= value %>
                  </div>
                <% end %>
            <% end %>
            <%= form_tag('/stripe_charge_check',{method: :post, autocomplete: :"off"})  do  %>
                <div class="plan">
                    <%= hidden_field_tag "plan_id", "Enterprise" %>
                    <%= hidden_field_tag "amount", 3900 %>
                    <%= hidden_field_tag "charge", 1 %>
                    <p>
                    </p>
                    <h3><%= 'Enterprise' %><span>$<%= 39 %></span></h3>
                    <ul>
                        <li>Daily Vendor Suggestions</li>
                        <li>Analysis up to 100k Sku Catalogs Daily</li>
                        <li>Membership rates for Prep and Pack</li>
                    </ul>
                    <div class= "buttons">
                        <!-- <button type="submit" class="pay-btn"><span>Choose Plan</span></button> -->
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button paybtn"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="A month's subscription"
                            data-amount=<%= 3900 %>
                            data-locale="auto">
                        </script>
                    </div>
                </div>
            <% end %>
        </div>  
  </div>

</div>

 <script>
    
    /*var buttons = document.getElementsByClassName("stripe-button-el");
    for (var i=0; i < buttons.length; i++){
      document.getElementsByClassName("stripe-button-el")[i].children[0].innerText = 'Start Free Trail';  
      document.getElementsByClassName("stripe-button-el")[i].addEventListener("click", onClickTrialButton);
    }
    
    function onClickTrialButton(){

      var iframe = document.getElementsByTagName("iframe");
      console.log(iframe);
      var iframeDoc = (iframe[0].contentDocument) ? iframe[0].contentDocument : iframe[0].contentWindow.document;
      iframeDoc.getElementsByClassName("Button-content")[0].children[0].innerText="Start Free Trial";
      iframeDoc.getElementsByClassName("Button-content")[0].children[0].children[0].children[0].innerText="";
    }*/
  </script>

app/views/subscriptions/stripe_notification.html.erb
<div class="modal-dialog col-6 col-m-11 mymodal" style="margin: auto;">
  <div class="modal-content">
    <div class="centermodal">
      <div class="">        
        <div class="text-center">
          <p class="modal-title">Welcome from Steven Rozen, FBA Support's CEO</p>
        </div>        
      </div>
      <hr>
      <div class="modal-body">
        <p>
          Unfortuantely, Your trial has expired. Please upgrade your  <%= link_to('subscription', plans_path)  %> , or feel free to <a href="https://calendly.com/fba-steve" style="text-decoration: underline">schedule a chat</a> to ask any questions.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/welcome.html.erb
<div class="modal-dialog col-6 col-m-11 mymodal">
  <div class="modal-content">
    <div class="centermodal">
      <div class="">        
        <div class="text-center">
          <img src="/images/coach/cto.png" class="rounded">
          <p class="modal-title">Welcome from Steven Rozen, FBA Support's CEO </p>
        </div>        
      </div>
      <hr>
      <div class="modal-body">
        <p><b>Thanks - your account's ready to go!</b></p>
        <p>
          Our goal with FBA.support is to eliminate tedious tasks that take up long hours. We have perfected the model for reselling wholesale on Amazon USA. Dig in and explore!<br>
          If you ever need a hand, a vendor, or even some tips on how to start sales with FBA.support please contact me directly at <a href="mailto:>steven@fba.support" target="_blank"><span style="color:blue">steven@fba.support</span></a>
        </p>
        <p>Thanks again and all the best</p>
        <br>
        <p class="sign"><i>Steven</i></p>
        <br>
        <a href="<%= new_skynet_path %>" class="btn btn-lg btn-info pull-right gobtn">OK! Let's see my account -></a>
      </div>
    </div>
  </div>
</div>